import { useState } from 'react'
import { Activity, BrainCircuit, ChartNoAxesCombined, Check, CircleAlert, Database, FileText, Layers3, Network, Newspaper, ShieldAlert, SlidersHorizontal, Waypoints } from 'lucide-react'

type Capability = 'fingerprint' | 'anomaly' | 'correlation' | 'risk'

const configurations = {
  fingerprint: { eyebrow: 'ADAPTIVE BEHAVIOURAL FINGERPRINTING', title: 'Build an asset-specific market baseline.', intro: 'Compare a current observation against an adaptive behavioural profile. This prototype visualises the intended analysis workspace.', icon: BrainCircuit },
  anomaly: { eyebrow: 'MULTI-SOURCE ANOMALY DETECTION', title: 'Surface unusual movement with context.', intro: 'Bring market, volume and sentiment observations into a single anomaly-review surface. Values shown here are illustrative.', icon: Activity },
  correlation: { eyebrow: 'CROSS-SOURCE EVENT CORRELATION', title: 'Connect events across time and sources.', intro: 'Explore how market movement, news and sentiment could form contextual evidence around one market event.', icon: Waypoints },
  risk: { eyebrow: 'RISK SCORING & EVIDENCE CHAIN', title: 'Make the risk signal explainable.', intro: 'Review a transparent evidence chain behind an illustrative risk score. This is not investment advice or a market prediction.', icon: ChartNoAxesCombined },
} satisfies Record<Capability, { eyebrow: string; title: string; intro: string; icon: typeof BrainCircuit }>

function FingerprintVisual() { const [window, setWindow] = useState('30D'); return <div className="demo-visual fingerprint-visual"><div className="demo-toolbar"><span>RELIANCE · NSE</span><div>{['7D', '30D', '90D'].map(item => <button className={window === item ? 'active' : ''} onClick={() => setWindow(item)} key={item}>{item}</button>)}</div></div><div className="fingerprint-stage"><div className="fingerprint-ring ring-one" /><div className="fingerprint-ring ring-two" /><div className="fingerprint-ring ring-three" /><div className="fingerprint-core"><BrainCircuit size={29}/><strong>BASELINE</strong><small>{window} WINDOW</small></div><span className="fingerprint-tag tag-price">PRICE<br/><b>Normal</b></span><span className="fingerprint-tag tag-volume">VOLUME<br/><b>Elevated</b></span><span className="fingerprint-tag tag-temporal">TEMPORAL<br/><b>Stable</b></span></div><div className="demo-footnote"><Check size={13}/> Profile is illustrative · adaptive model planned</div></div> }

function AnomalyVisual() { const [threshold, setThreshold] = useState(68); return <div className="demo-visual anomaly-visual"><div className="demo-toolbar"><span>ANOMALY REVIEW</span><span className="signal-status"><i/> MONITORING</span></div><div className="anomaly-chart">{[28,34,31,38,35,49,42,63,54,78,59,71].map((value,index) => <i style={{ height: `${value}%` }} className={value > threshold ? 'alert' : ''} key={index} />)}<div className="threshold-line" style={{ bottom: `${threshold}%` }}><span>Threshold {threshold}</span></div></div><label className="threshold-control">Sensitivity <input type="range" min="40" max="85" value={threshold} onChange={event => setThreshold(Number(event.target.value))}/><strong>{threshold}</strong></label><div className="signal-grid"><span><Database size={14}/> Market data</span><span><Newspaper size={14}/> News signals</span><span><Activity size={14}/> Volume pattern</span></div></div> }

function CorrelationVisual() { const [focus, setFocus] = useState('Market move'); const nodes = [['Market move', Activity], ['News item', Newspaper], ['Sentiment', BrainCircuit], ['Time window', Layers3]] as const; return <div className="demo-visual correlation-visual"><div className="demo-toolbar"><span>EVENT GRAPH</span><Network size={16}/></div><div className="correlation-stage"><div className="event-link link-a"/><div className="event-link link-b"/><div className="event-link link-c"/><div className="event-core"><span>CONTEXT</span><strong>EVENT</strong></div>{nodes.map(([label, Icon], index) => <button className={`event-node node-${index} ${focus === label ? 'focused' : ''}`} onClick={() => setFocus(label)} key={label}><Icon size={17}/><span>{label}</span></button>)}</div><div className="event-summary"><span>Focused signal</span><strong>{focus}</strong><small>Illustrative correlation path</small></div></div> }

function RiskVisual() { const [expanded, setExpanded] = useState(false); return <div className="demo-visual risk-visual"><div className="demo-toolbar"><span>EXPLAINABLE RISK</span><ShieldAlert size={16}/></div><div className="risk-content"><div className="risk-orb"><div><strong>62</strong><span>RISK SCORE</span></div></div><div className="evidence-list"><button onClick={() => setExpanded(!expanded)}><CircleAlert size={15}/><span>Volume deviation</span><b>+24</b></button><button><Newspaper size={15}/><span>News sentiment</span><b>+18</b></button><button><FileText size={15}/><span>Temporal context</span><b>+20</b></button></div></div>{expanded && <div className="evidence-detail"><SlidersHorizontal size={14}/> Volume is above its illustrative baseline.</div>}<div className="demo-footnote">Illustrative score · review evidence before action</div></div> }

export function CapabilityDemoPage({ capability }: { capability: Capability }) {
  const config = configurations[capability]; const Icon = config.icon
  const visual = capability === 'fingerprint' ? <FingerprintVisual/> : capability === 'anomaly' ? <AnomalyVisual/> : capability === 'correlation' ? <CorrelationVisual/> : <RiskVisual/>
  return <main className="capability-page"><section className="capability-hero"><div className="container capability-grid"><div><p className="eyebrow">{config.eyebrow}</p><h1 className="section-title">{config.title}</h1><p className="section-intro">{config.intro}</p><a className="back-link" href="/#services">← Back to services</a></div><div className="capability-panel"><div className="panel-badge"><Icon size={16}/> AVENTRA PROTOTYPE</div>{visual}</div></div></section></main>
}
