"""SYNTHETIC test provider for the TEST:DEMO instrument (data/demo, generated by scripts/generate_demo_data.py).

Registered ONLY when AVENTRA_ENABLE_SYNTHETIC_TEST_DATA=1 (the automated test-suite). It is never a fallback for
real instruments and never appears in user-facing deployments.
"""
from __future__ import annotations

import pandas as pd

from ml import config
from ml.instruments.master import alias_rows, instrument_row
from ml.providers.base import InstrumentNotSupported, Provider, ProviderCapability, Series

TEST_ID = "TEST:DEMO"


class SyntheticTestProvider(Provider):
    name = "aventra_demo_dataset"
    is_synthetic = True
    capability = ProviderCapability(asset_classes=("equity",), exchanges=("TEST",), fields=("open", "high", "low", "close", "volume"), listing=True,
                                    terms="Synthetic test fixture: automated tests only.")

    def history(self, instrument: dict, provider_symbol: str, start=None) -> Series:
        path = config.DEMO_DIR / "market.csv"
        if instrument.get("instrument_id") != TEST_ID or not path.is_file():
            raise InstrumentNotSupported("Synthetic test data is only available for TEST:DEMO.", self.name)
        frame = pd.read_csv(path)
        frame["timestamp"] = pd.to_datetime(frame["timestamp"], utc=True)
        return Series(frame[["timestamp", "open", "high", "low", "close", "volume"]].copy(), self.name, "DEMO", "INR", "Asia/Kolkata",
                      meta={"synthetic": True})

    def list_instruments(self):
        row = instrument_row(TEST_ID, "DEMO", "Aventra Synthetic Test Asset", "equity", "TEST", currency="INR", source="synthetic_test_fixture",
                             class_source="test", class_confidence=1.0)
        row.update(timezone="Asia/Kolkata", calendar_code="XBOM")
        return [row], alias_rows(TEST_ID, strong=["Aventra Demo Asset"], source="test"), [{"instrument_id": TEST_ID, "provider": self.name, "provider_symbol": "DEMO", "priority": 1}]
