"""initial multi-asset schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 22:51:53.107332
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.String(length=96), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pipeline_version', sa.String(length=24), nullable=False),
    sa.Column('feature_set_version', sa.String(length=64), nullable=True),
    sa.Column('data_through', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_source', sa.JSON(), nullable=True),
    sa.Column('models', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_instrument', ['instrument_id', 'created_at'], unique=False)

    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.String(length=120), nullable=False),
    sa.Column('run_id', sa.String(length=96), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statistical_score', sa.Float(), nullable=True),
    sa.Column('fingerprint_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_anomalies_instrument', ['instrument_id', 'ts'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('anomaly_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_anomaly', ['anomaly_id'], unique=False)
        batch_op.create_index('ix_events_instrument', ['instrument_id', 'start_time'], unique=False)

    op.create_table('evidence',
    sa.Column('anomaly_id', sa.String(length=120), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('linked_url', sa.Text(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('anomaly_id', 'seq')
    )
    op.create_table('fingerprints',
    sa.Column('run_id', sa.String(length=96), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('instruments',
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('exchange', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.Column('calendar_code', sa.String(length=24), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('class_source', sa.String(length=48), nullable=True),
    sa.Column('class_confidence', sa.Float(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('benchmark_id', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index('ix_instruments_class', ['asset_class', 'exchange'], unique=False)
        batch_op.create_index('ix_instruments_isin', ['isin'], unique=False)
        batch_op.create_index('ix_instruments_symbol', ['symbol'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_dedupe', ['dedupe_key', 'status'], unique=False)
        batch_op.create_index('ix_jobs_ready', ['status', 'run_after', 'priority'], unique=False)

    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('news_id', sa.String(length=40), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('news_id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index('ix_news_published', ['published_at'], unique=False)

    op.create_table('prices',
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_symbol', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.Column('adjusted', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.UniqueConstraint('instrument_id', 'interval', 'ts', 'provider', name='uq_price_bar')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index('ix_prices_lookup', ['instrument_id', 'interval', 'ts'], unique=False)

    op.create_table('provider_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.create_index('ix_provider_calls_recent', ['provider', 'occurred_at'], unique=False)

    op.create_table('risks',
    sa.Column('assessment_id', sa.String(length=130), nullable=False),
    sa.Column('anomaly_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=12), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instrument_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('alias_norm', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'alias_norm', 'kind', name='uq_alias')
    )
    with op.batch_alter_table('instrument_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_alias_norm', ['alias_norm'], unique=False)

    op.create_table('news_links',
    sa.Column('news_id', sa.String(length=40), nullable=False),
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('entity_match_confidence', sa.Float(), nullable=False),
    sa.Column('mapping_method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'instrument_id')
    )
    with op.batch_alter_table('news_links', schema=None) as batch_op:
        batch_op.create_index('ix_news_links_instrument', ['instrument_id'], unique=False)

    op.create_table('provider_symbols',
    sa.Column('instrument_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_symbol', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'provider')
    )
    with op.batch_alter_table('provider_symbols', schema=None) as batch_op:
        batch_op.create_index('ix_provider_symbol_lookup', ['provider', 'provider_symbol'], unique=False)

    op.create_table('sentiment',
    sa.Column('news_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=12), nullable=False),
    sa.Column('positive_probability', sa.Float(), nullable=True),
    sa.Column('neutral_probability', sa.Float(), nullable=True),
    sa.Column('negative_probability', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment')
    with op.batch_alter_table('provider_symbols', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_symbol_lookup')

    op.drop_table('provider_symbols')
    with op.batch_alter_table('news_links', schema=None) as batch_op:
        batch_op.drop_index('ix_news_links_instrument')

    op.drop_table('news_links')
    with op.batch_alter_table('instrument_aliases', schema=None) as batch_op:
        batch_op.drop_index('ix_alias_norm')

    op.drop_table('instrument_aliases')
    op.drop_table('watchlists')
    op.drop_table('risks')
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_calls_recent')

    op.drop_table('provider_calls')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index('ix_prices_lookup')

    op.drop_table('prices')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_published')

    op.drop_table('news')
    op.drop_table('listing_snapshots')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_ready')
        batch_op.drop_index('ix_jobs_dedupe')

    op.drop_table('jobs')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index('ix_instruments_symbol')
        batch_op.drop_index('ix_instruments_isin')
        batch_op.drop_index('ix_instruments_class')

    op.drop_table('instruments')
    op.drop_table('fingerprints')
    op.drop_table('evidence')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_instrument')
        batch_op.drop_index('ix_events_anomaly')

    op.drop_table('events')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anomalies_instrument')

    op.drop_table('anomalies')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_instrument')

    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
