import { useState } from 'react'
import { ArrowRight, BarChart3, Sparkles } from 'lucide-react'
import { analyzeNews, type NewsAnalysisResult } from '../../services/newsApi'

const probabilityRows: Array<[keyof Pick<NewsAnalysisResult, 'positive_probability' | 'neutral_probability' | 'negative_probability'>, string]> = [
  ['positive_probability', 'Positive'], ['neutral_probability', 'Neutral'], ['negative_probability', 'Negative'],
]

export function NewsAnalysis() {
  const [text, setText] = useState(''); const [result, setResult] = useState<NewsAnalysisResult>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!text.trim()) { setError('Enter financial news to begin analysis.'); setResult(undefined); return } setLoading(true); setError(''); try { setResult(await analyzeNews({ text })) } catch (reason) { setResult(undefined); setError(reason instanceof Error ? reason.message : 'Unable to analyse the text. Please try again.') } finally { setLoading(false) } }
  return <section className="section news-analysis" id="news-analysis"><div className="container news-analysis-grid"><div className="news-analysis-copy"><p className="eyebrow">AI FINANCIAL NEWS ANALYSIS</p><h1 className="section-title">Understand financial language in context.</h1><p className="section-intro">Analyse financial text with Aventra’s FinBERT sentiment-classification pipeline. Sentiment is a contextual signal, not a market prediction or financial advice.</p><div className="finbert-note"><Sparkles size={16} /><span>FINBERT SENTIMENT CLASSIFICATION</span></div></div><div className="news-analysis-card"><form onSubmit={submit}><label htmlFor="news-text">Financial news or text</label><textarea id="news-text" value={text} onChange={(event) => setText(event.target.value)} maxLength={12000} placeholder="Enter financial news or text here…" aria-describedby="news-text-count" /><div className="news-form-footer"><span id="news-text-count">{text.length.toLocaleString()} / 12,000</span><button className="analyze-button" disabled={loading}>{loading ? 'Analysing…' : <>Analyze News <ArrowRight size={15}/></>}</button></div></form>{!result && !error && !loading && <p className="analysis-state" aria-live="polite">Enter financial news to begin analysis.</p>}{loading && <p className="analysis-state" role="status"><BarChart3 size={15} className="spinning" /> Analysing financial text…</p>}{error && <p className="analysis-error" role="alert">{error}</p>}{result && <div className="sentiment-result" aria-live="polite"><div className="result-heading"><span>ANALYSIS RESULT</span><strong className={`sentiment-${result.label}`}>{result.label}</strong></div><div className="result-summary"><div><span>Confidence</span><strong>{Math.round(Math.max(result.positive_probability, result.neutral_probability, result.negative_probability) * 100)}%</strong></div><div><span>Sentiment score</span><strong>{result.sentiment_score >= 0 ? '+' : ''}{result.sentiment_score.toFixed(2)}</strong></div></div><div className="probabilities">{probabilityRows.map(([key, label]) => <div className="probability" key={key}><div><span>{label}</span><strong>{Math.round(result[key] * 100)}%</strong></div><i><b className={`bar-${label.toLowerCase()}`} style={{ width: `${Math.max(0, Math.min(100, result[key] * 100))}%` }} /></i></div>)}</div></div>}</div></div></section>
}
